apiVersion: batch/v1
kind: Job
metadata:
  name: detection-test
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: detection-test
        image: kckuhns92/openshift-detection-container:latest
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          seccompProfile:
            type: RuntimeDefault
      restartPolicy: Never
